### ISSUE TITLE
Add finalized content to our services section

### ISSUE THREAD

**Issue by jtorreggiani** [specollective/spec-frontend#101]
Each section should have a title, subtitle, expanded description, and an image.

- [ ] Engaged Research
- [ ] Collaborative Mentorship
- [ ] Applied Learning
- [ ] Capacity Building
- [ ] Career Pathways

**Comment by iliadeleon** [comment]
Content is ready as per Figma fies for [Desktop](https://www.figma.com/file/0mW24BOnbrxQodmg6GOxqA/Website-Redesign?type=design&node-id=2990-4281&mode=design&t=aPyM6Rd2ugDUXKgs-11) and [Mobile](https://www.figma.com/file/0mW24BOnbrxQodmg6GOxqA/Website-Redesign?type=design&node-id=2990-4847&mode=design&t=aPyM6Rd2ugDUXKgs-11). 

Below are screenshots of the default and expanded versions. 

 ![Screenshot 2023-08-24 at 9 39 05 AM](https://github.com/specollective/spec-frontend/assets/88496806/1ddac238-8b88-4e47-8c83-a50322d16f0f)
![Screenshot 2023-08-24 at 9 40 57 AM](https://github.com/specollective/spec-frontend/assets/88496806/cd60a027-130c-4ce1-bba8-755aa2c3af0f)

Let me know if you have any questions. Thanks!
