### ISSUE TITLE
Add finalized content to informational sections

### ISSUE THREAD

**Issue by jtorreggiani** [specollective/spec-frontend#111]
Update the follow sections to match the [Figma](https://www.figma.com/file/0mW24BOnbrxQodmg6GOxqA/Website-Redesign?type=design&node-id=2-2&mode=design&t=KfeIJPT6VbcBtmEr-0)

- [ ] Add copy and image for the "our mission" section
- [ ] Add copy and image for the "our history" section
- [ ] Add copy and image for the "how we work" section
- [ ] Add copy and image copy for the "what we do" section

Note: the title copy font and syntax should match the Figma design.

**Comment by najwanan** [comment]
The padding for the information sections on the home page is not consistent. Vertical and horizontal padding should match the Figma (or best approximation if it doesn't match the current version).
