### ISSUE TITLE
By the Numbers section Update: Mobile and Desktop

### ISSUE THREAD

**Issue by iliadeleon** [specollective/spec-frontend#137]
**Update**

- [x] By the Numbers content (within the white boxes) was changed has been updated on both mobile and desktop

![Screenshot 2023-09-13 at 1 50 44 PM](https://github.com/specollective/spec-frontend/assets/88496806/b9672eaf-84e1-4b8b-85d6-70af52d67d4c)

**Comment by crystallynnvoss** [comment]
@iliadeleon I noticed that on the Figma, on the last 2 cards in by the numbers, the text is left aligned, on the first two it is centered, is there a preference?
