### ISSUE TITLE
Mobile View - Hero Image is not on the right side of page

### ISSUE THREAD

**Issue by iliadeleon** [specollective/spec-frontend#56]
Alignment is off. Image more centered than to the right. No margin on left side

![IMG_7181](https://user-images.githubusercontent.com/88496806/236272214-b84b5037-e912-4c23-9e25-2dfdd2a5fca3.jpg)

**Comment by najwanan** [comment]
<img width="350" alt="Screenshot 2023-07-12 at 12 10 15 AM" src="https://github.com/specollective/spec-frontend/assets/66931010/162b0ea2-c779-4b02-b969-b987141ee0de">
Resolved through other PR's
