### ISSUE TITLE
Mission

### ISSUE THREAD

**Issue by EmmaBin** [specollective/spec-frontend#7]
- [ ] Image
- [ ] Title "OUR MISSION"
- [ ] Header "Empower individuals to..."
- [ ] Description "We understand that for..."
![Screen Shot 2023-04-04 at 2 43 08 PM](https://user-images.githubusercontent.com/63168510/229929441-2089c9d2-3eb7-4ccc-9738-ebf076fb9a36.png)

**Comment by iliadeleon** [comment]
Additional section under Mission.

- [ ] **Figma Link:** https://www.figma.com/file/0mW24BOnbrxQodmg6GOxqA/Website-Redesign?node-id=2098-4006&t=JWO5SVXfhlaTNCrn-11 (This is on the V1 content frame)
- [ ] **Image:** https://drive.google.com/file/d/1fc7Ne5e5v4jN6CfmfyQrVZUdJ-PkeTz_/view?usp=share_link
- [ ] **Link to Buffalo Project website:** https://thebuffaloproject.wixsite.com/tbpinternship

![Screen Shot 2023-04-24 at 3 15 58 PM](https://user-images.githubusercontent.com/88496806/234094629-814cbf5f-fc6a-4c18-8ee9-0924ca40b041.png)
