### ISSUE TITLE
Update Get Involved Section

### ISSUE THREAD

**Issue by iliadeleon** [specollective/spec-frontend#86]
- [x] #96
- [x] Use the contribution tiers as the primary image
- [x] Remove learn more show more info interaction
- [x] Link to documentation site (we can choose the specific page later)
- [x] Donate button is the incorrect shape (can match back to the Navbar button update)
- [x] Body copy font is incorrect, should be Montserrat
- [x] Donate Learn More image/chart should be larger
- [x] Donate Learn More needs updated copy (cannot be blank)
- [x] Donate button should open OC in a new window
- [x] Contact Us button doesn't anchor to the Contact form at the bottom of the page
- [x] Make sure "Contact Us" is center aligned to the card
- [x] In carousel all cards should be the same size

**Comment by greenhacks** [comment]
@iliadeleon Closing out since the tasks have either been completed or broken down into small chunks (#133).
