### ISSUE TITLE
Update Projects Section

### ISSUE THREAD

**Issue by iliadeleon** [specollective/spec-frontend#87]
Blurb + Accordion

- [x] Project portion is off the grid from the others (mission and BP) see images
- [x] Project image is bigger than the others on desktop but smaller than others on mobile? see images
- [x] Project header and image get too small on mobile. Acts different than the other sections
- [ ] All external links should open in new tab
- [x] Update links in each snapshot https://github.com/specollective/spec-frontend/issues/82

![Screenshot 2023-07-17 at 2 24 09 PM](https://github.com/specollective/spec-frontend/assets/88496806/d276aa0b-ff3b-4f9b-8fe6-608c5b55d07a)

![Screenshot 2023-07-17 at 2 22 53 PM](https://github.com/specollective/spec-frontend/assets/88496806/eabfa5dd-7c23-416d-a7ce-9451062fdd32)

**Comment by najwanan** [comment]
ticket 82 has been merged in
